### ISSUE TITLE
Great package

### ISSUE THREAD

**Issue by mshd** [ridafkih/schemix#5]
Hi thanks for the package, it seems quite needed. Forgive me I'm new to Prisma but I have a few questions:

1. Can it support a schemas from other packages see: https://github.com/investycorp/prisma-schema-import
2. Can schemas be extended from other packages, like adding timestampable/blameable to certain tables.
3. Can one external npm package's schema be integrated in the project schema
4. Possible to convert typescript types into schema?

**Comment by ridafkih** [comment]
Hey! Thanks for opening an issue! ✨ 

1. Since the schema is generated from TypeScript code, it doesn't have the ability to support importing models from other `.prisma` files. Would this functionality be useful to you? I could see to adding it if so, something like... 

```ts
// Proposal:
const schema = createSchema({ datasource, generator });

const model = schema.importModel("./model.prisma");
```

2. Schemas can't be extended from other packages, but I did implement a mixin functionality that would allow you to implement tables without repeating yourself.

```ts
const schema = createSchema({ datasource, generator });

const dateMixin = schema.createMixin()
  .dateTime("createdAt", { default: { now: true } })
  .dateTime("updatedAt", { updatedAt: true });

const model = schema.createModel();

model
  .string("id", { id: true, default: { uuid: true } })
  .mixin(dateMixin);

schema.export(/** ... */);
```

3. If the package exports a Schemix object, that could totally be possible, I could also add a schema import functionality that would allow for such functionality if that's something you'd be interested in. 

4. Unfortunately not, since the TypeScript types are not present at runtime. :(
